#:schema node_modules/wrangler/config-schema.json

name = "eplayerx-homepage"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

# 填入你刚才截图中的区域 ID
zone_id = "1d216f8f5c76c12b32acadba4ae8c90d"

# Keep the default *.workers.dev address alive.
workers_dev = true

# Public routes for this Worker.
# Cloudflare 会通过上面配置的 zone_id 自动识别这些域名属于哪个区域
routes = [
	{ pattern = "api.chenluo.cyou/*", custom_domain = true },
	{ pattern = "tmdb.chenluo.cyou/*", custom_domain = true },
	{ pattern = "chenluo.cyou/blocks*", zone_name = "chenluo.cyou" },
]

[placement]
mode = "smart"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "eplayerx-homepage"
database_id = "7a464001-94aa-4eca-85b5-5a7a9beb16a9"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "crawler"
